{
  inputs = {
    chaotic = {
      url = "github:chaotic-cx/nyx/nyxpkgs-unstable";
    };
    home-manager = {
      follows = "chaotic/home-manager";
    };
    "icedos-github:icedos/apps" = {
      url = "github:icedos/apps/32025a3a205f9c93ac6e1bd976e6f1a39fc121dc";
    };
    "icedos-github:icedos/apps-celluloid-celluloid-shader" = {
      flake = false;
      url = "path:///nix/store/5zcj323fgw0vxx0nhgvp45yxrwikm0c6-FSR.glsl";
    };
    "icedos-github:icedos/desktop" = {
      url = "github:icedos/desktop/e720157c85d93303164852489e928870e2e3c08f";
    };
    "icedos-github:icedos/gnome" = {
      url = "github:icedos/gnome/16a6fc3084ea50e611bcef13a01a885fbb19016d";
    };
    "icedos-github:icedos/hardware" = {
      url = "github:icedos/hardware/e64d5f9748968352822f72dad2e30dfce0aa27d1";
    };
    "icedos-github:icedos/providers" = {
      url = "github:icedos/providers/1273fe1a4086fbe2a84436ca1acb350a0020a410";
    };
    "icedos-github:icedos/tweaks" = {
      url = "github:icedos/tweaks/83d42744d78c418a259b8e1c4ae7eba1d3e9eaf5";
    };
    "icedos-github:icedos/users" = {
      url = "github:icedos/users/9ddc3663045cd05e7df3d99844b4b640741fe667";
    };
    nixpkgs = {
      follows = "chaotic/nixpkgs";
    };

  };

  outputs =
    {
      home-manager,
      nixpkgs,
      self,
      ...
    }@inputs:
    let
      system = "x86_64-linux";
      pkgs = nixpkgs.legacyPackages.${system};
      inherit (pkgs) lib;
      inherit (lib) fileContents flatten map;

      inherit (builtins) fromTOML;
      inherit ((fromTOML (fileContents ./config.toml))) icedos;

      icedosLib = import ./lib.nix {
        inherit lib pkgs inputs;
        config = icedos;
        self = ./.;
      };

      inherit (icedosLib) getExternalModuleOutputs;

      externalModulesOutputs = map getExternalModuleOutputs icedos.repositories;

      extraOptions = flatten (map (mod: mod.options) externalModulesOutputs);

      extraNixosModules = flatten (
        map (mod: mod.nixosModules { inherit inputs; }) externalModulesOutputs
      );
    in
    {
      apps.${system}.init = {
        type = "app";
        program = toString (with pkgs; writeShellScript "icedos-flake-init" "exit");
      };

      nixosConfigurations."nixos" = nixpkgs.lib.nixosSystem rec {
        specialArgs = {
          inherit icedosLib inputs;
        };

        modules = [
          # Read configuration location
          (
            { lib, ... }:
            let
              inherit (lib) mkOption types;
            in
            {
              options.icedos.configurationLocation = mkOption {
                type = types.str;
                default = "/home/giannis/code/os-config";
              };
            }
          )

          # Symlink configuration state on "/run/current-system/source"
          {
            # Source: https://github.com/NixOS/nixpkgs/blob/5e4fbfb6b3de1aa2872b76d49fafc942626e2add/nixos/modules/system/activation/top-level.nix#L191
            system.extraSystemBuilderCmds = "ln -s ${self} $out/source";
          }

          # Internal modules and config
          (
            { lib, ... }:
            let
              inherit (lib) filterAttrs;

              getModules =
                path:
                map (dir: "/${path}/${dir}") (
                  let
                    inherit (lib) attrNames;
                  in
                  attrNames (filterAttrs (n: v: v == "directory") (builtins.readDir path))
                );
            in
            {
              imports = [ ./options.nix ] ++ getModules ./.extra ++ getModules ./.private;
              config.system.stateVersion = "24.05";
            }
          )

          home-manager.nixosModules.home-manager

          { icedos.system.isFirstBuild = false; }

          (
            # Do not modify this file!  It was generated by ‘nixos-generate-config’
            # and may be overwritten by future invocations.  Please make changes
            # to /etc/nixos/configuration.nix instead.
            {
              config,
              lib,
              pkgs,
              modulesPath,
              ...
            }:

            {
              imports = [
                (modulesPath + "/installer/scan/not-detected.nix")
              ];

              boot.initrd.availableKernelModules = [
                "nvme"
                "xhci_pci"
                "ahci"
                "usbhid"
                "usb_storage"
                "sd_mod"
              ];
              boot.initrd.kernelModules = [ ];
              boot.kernelModules = [ "kvm-amd" ];
              boot.extraModulePackages = [ ];

              fileSystems."/" = {
                device = "/dev/disk/by-uuid/051448c2-f19b-4d84-b91b-f38d494996a5";
                fsType = "btrfs";
                options = [ "subvol=@" ];
              };

              boot.initrd.luks.devices."luks-fb7a7159-bb31-4bfc-9147-e20b16ec99f9".device =
                "/dev/disk/by-uuid/fb7a7159-bb31-4bfc-9147-e20b16ec99f9";

              fileSystems."/boot" = {
                device = "/dev/disk/by-uuid/4914-28AB";
                fsType = "vfat";
                options = [
                  "fmask=0022"
                  "dmask=0022"
                ];
              };

              # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
              # (the default) this is the recommended approach. When using systemd-networkd it's
              # still possible to use this option, but it's recommended to use it in conjunction
              # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
              networking.useDHCP = lib.mkDefault true;
              # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
              # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

              nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
              hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
            }
          )

          ({ })

        ]
        ++ extraOptions
        ++ extraNixosModules;
      };
    };
}
